$(document).ready(function(){
	$('input#zModelSearch').jsonSuggest(zModelSearch,{ajaxResults:true,maxResults:5, minCharacters: 2,width:300,onSelect:searchSelect});
	//modalWindow
	winDiv=$("#winDiv").val();
	$("a[name=modal]").on("click",function(e){e.preventDefault();var id=$(this).attr("href");id=id.substring(id.indexOf("#"));var maskHeight=$(document).height();var maskWidth=$(window).width();$("#mask").css({width:maskWidth,height:maskHeight});$("#mask").fadeIn(500);$("#mask").fadeTo("slow",0.8);var winH=$(window).height();var winW=$(window).width();$(id).css("top",winH/winDiv-$(id).height());$(id).css("left",winW/2-$(id).width()/2);$(id).fadeIn(500);});
	$(".window .close").click(function(e){e.preventDefault();$("#mask").hide();$(".window").hide();$(".loginLoading").hide();});
	$("#mask").click(function(){$(this).hide();$(".window").hide();$(".loginLoading").hide();});
});

function openSignin(op){$(".loginLoading").show();if(op=="google"){openid_identifier="https://www.google.com/accounts/o8/id";}else{if(op=="yahoo"){openid_identifier="https://me.yahoo.com";}else{return;}}$("#openid_identifier").val(openid_identifier);$("#openLoginForm").submit();}
function fbLogin(){$(".loginLoading").show();FB.login(function(response){if(response.authResponse){FB.getLoginStatus(function(response){authenticate(response);});}else{$(".loginLoading").hide();}},{scope:"email,user_checkins"});}
function authenticate(response){if(response.status==="connected"){FB.api("/me",function(user){if($.isEmptyObject(user)==false){$("#fbUserName").val(user.name);$("#fbUserEmail").val(user.email.toString());$("#fbLoginForm").submit();}});}else{$(".fb_button").click();FB.Event.subscribe("auth.login",function(response){authenticate(response);});}}
function showMenu(thisLi,me){$(thisLi).addClass("current_page_item");$("#home").removeClass("current_page_item");$("#"+me).show();}
function hideMenu(thisLi,me){$(thisLi).removeClass("current_page_item");$("#home").addClass("current_page_item");$("#"+me).hide();}
function $import(src){var scriptElem=document.createElement("script");scriptElem.setAttribute("src",src);scriptElem.setAttribute("type","text/javascript");scriptElem.setAttribute("async",true);(document.getElementsByTagName("head")[0]||document.getElementsByTagName("body")[0]).appendChild(scriptElem);}
function $importNoCache(src){var ms=new Date().getTime().toString();var seed="?"+ms;$import(src+seed);}
var searchResult={};
function zModelSearch(text){var d=new Date();$("#zModelSearchForm_searchBtn").attr('disabled',false);var deviceId=$("#zModelSearchForm_deviceId").val();$.ajax({url:"zModelSearch_DeviceAjaxAction.html?_="+d.getTime()+"&dId="+deviceId+"&searchStr="+text,async:false,dataType:"json",success:function(result){searchResult=result.modelSearchList;}});return searchResult;}
function searchSelect(data){$("#zModelSearchForm_searchMId").val(data.id);$("#zModelSearchForm").attr("action","modelDetail.html");$("#zModelSearchForm").submit();}
//welcome.js
function getDeviceReviewList(){var d=new Date();$.get("fetchDeviceLatestReviews_DeviceAjaxAction.html?_="+d.getTime()+"&dId=1",null,function(data){if(data.deviceReviewList.length>0){var reviewContainer='<li><a href="{contextPath}{refLink}#{reviewId}" title="{modelName} : {title}"><img class="modelReviewThumbImg" src="{modelImageSrc}" alt="{modelName} : {title}" height="110" /><div id="modelReviewDesc"><div class="titlec">{modelName} : {title}<div class="reviewBy">- By {author}  on {reviewDate}</div></div><div class="desc">{review}</div></div></a></li>';$.each(data.deviceReviewList,function(index,item){var reviewContainerIndex=reviewContainer.replace(/{title}/g,item.title);reviewContainerIndex=reviewContainerIndex.replace(/{modelImageSrc}/g,item.modelImageUrl);reviewContainerIndex=reviewContainerIndex.replace(/{author}/g,item.author);reviewContainerIndex=reviewContainerIndex.replace(/{reviewDate}/g,item.reviewDate);reviewContainerIndex=reviewContainerIndex.replace(/{review}/g,item.review);reviewContainerIndex=reviewContainerIndex.replace(/{deviceId}/g,item.deviceId);reviewContainerIndex=reviewContainerIndex.replace(/{brandId}/g,item.manufacturerId);reviewContainerIndex=reviewContainerIndex.replace(/{modelId}/g,item.modelId);reviewContainerIndex=reviewContainerIndex.replace(/{reviewId}/g,item.reviewId);reviewContainerIndex=reviewContainerIndex.replace(/{refLink}/g,item.refLink);reviewContainerIndex=reviewContainerIndex.replace(/{modelName}/g,item.modelName);reviewContainerIndex=reviewContainerIndex.replace(/{contextPath}/g,$("#contextPath").val());$("ul.reviewList").append(reviewContainerIndex);});}});}
function getTopRatedModels(){$("#loading").show();var dId=$("#deviceId").serialize();var d=new Date();if($("#deviceId").val()!=""){$.get($("#contextPath").val()+"/fetchTopRatedModels_DeviceAjaxAction.html?_="+d.getTime(),dId,function(data){if(data.modelList!=null&&data.modelList.length>0){$("#highlyRated").append('<div class="blockHeader">Top Rated Models</div>');var topRatedContainer='<div class="productThumb"><div style="float: left;"><a href="{contextPath}{modelLink}"><img src="{modelImageUrl}" class="model-thumb" alt="{modelName}" /></a><div class="raty" ><div id="{star}"></div><span class="ratyCount">{ratingCount}<SPAN> votes</SPAN></span></div></div><a href="{contextPath}{modelLink}"><span class="caption">{modelName}</span><span class="desc">{modelDesc} ...</span></a></div>';$.each(data.modelList,function(index,item){var topRatedContainerIndex=topRatedContainer.replace(/{modelName}/g,item.modelName);topRatedContainerIndex=topRatedContainerIndex.replace(/{modelDesc}/g,item.modelDesc.substring(0,80));topRatedContainerIndex=topRatedContainerIndex.replace(/{modelImageUrl}/g,item.modelImageUrl);topRatedContainerIndex=topRatedContainerIndex.replace(/{modelId}/g,item.modelId);topRatedContainerIndex=topRatedContainerIndex.replace(/{deviceId}/g,item.deviceId);topRatedContainerIndex=topRatedContainerIndex.replace(/{brandId}/g,item.manufacturerId);topRatedContainerIndex=topRatedContainerIndex.replace(/{price}/g,item.price);topRatedContainerIndex=topRatedContainerIndex.replace(/{star}/g,"star_"+index);topRatedContainerIndex=topRatedContainerIndex.replace(/{ratingCount}/g,item.ratingCount);topRatedContainerIndex=topRatedContainerIndex.replace(/{starRating}/g,item.starRating);topRatedContainerIndex=topRatedContainerIndex.replace(/{contextPath}/g,$("#contextPath").val());topRatedContainerIndex=topRatedContainerIndex.replace(/{modelLink}/g,item.modelLink);$("#highlyRated").append(topRatedContainerIndex);var rating=item.starRating;$("#star_"+index).raty({readOnly:true,hints:["Bad","Poor","Average","Good","Superb"],score:rating});});}else{$("#highlyRated").append('<div class="blockHeader">Top Rated Models</div><SPAN>No Models found</SPAN>');}$("#loading").hide();});}}
function trimTextField(field){field.value=field.value.replace(/^\s+|\s+$/g,"");while(field.value.match(/\s\s/g)){field.value=field.value.replace(/\s\s/g," ");}}